# Generated by Django 5.1.4 on 2024-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=64)),
                ("movie_length", models.IntegerField(default=0.0)),
                ("age_classification", models.IntegerField(default=0)),
            ],
        ),
    ]
