# Generated by Django 5.1.4 on 2024-12-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
