# Generated by Django 5.1.4 on 2024-12-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
