# Generated by Django 5.1.4 on 2025-01-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_movie_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="background_image",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
