# Generated by Django 5.1.4 on 2025-01-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_movie_background_image_movie_cast_movie_director_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(related_name="movies", to="movie.genre"),
        ),
    ]
