# Generated by Django 5.1.1 on 2024-12-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema_room", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemaroom",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
